const usersJson = [
  {
    id: 6,
    name: "Julia Rossi",
    username: "julia.r",
    img: "https://randomuser.me/api/portraits/women/66.jpg",
    profession: "Product Manager",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 7,
    name: "Akash Mehra",
    username: "a_mehra",
    img: "https://randomuser.me/api/portraits/men/77.jpg",
    profession: "Business Analyst",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 8,
    name: "Emma Wilson",
    username: "emmawilson",
    img: "https://randomuser.me/api/portraits/women/88.jpg",
    profession: "QA Engineer",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 1,
    name: "Amit Sharma",
    username: "amit_s",
    img: "https://randomuser.me/api/portraits/men/11.jpg",
    profession: "Software Engineer",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 2,
    name: "Sophie Dubois",
    username: "sophie_d",
    img: "https://randomuser.me/api/portraits/women/22.jpg",
    profession: "Graphic Designer",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 3,
    name: "Liam Smith",
    username: "liam_smith",
    img: "https://randomuser.me/api/portraits/men/33.jpg",
    profession: "DevOps Engineer",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 4,
    name: "Priya Patel",
    username: "priya_93",
    img: "https://randomuser.me/api/portraits/women/44.jpg",
    profession: "UX Designer",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 5,
    name: "Chen Wei",
    username: "chenw",
    img: "https://randomuser.me/api/portraits/men/55.jpg",
    profession: "Data Scientist",
    requestSent: false,
    isFriend: false,
  },

  {
    id: 9,
    name: "Carlos Ramirez",
    username: "carlos_rz",
    img: "https://randomuser.me/api/portraits/men/99.jpg",
    profession: "Mobile Developer",
    requestSent: false,
    isFriend: false,
  },
  {
    id: 10,
    name: "Nina Müller",
    username: "nina_mu",
    img: "https://randomuser.me/api/portraits/women/10.jpg",
    profession: "Content Writer",
    requestSent: false,
    isFriend: false,
  },
];
export default usersJson;
