const usersJson = [
  {
    id: 1,
    name: "Amit Sharma",
    username: "amit_s",
    img: "https://randomuser.me/api/portraits/men/15.jpg",
    profession: "Software Engineer",
    bio: "👨‍💻 Coding dreams into reality | ⚡ Full-stack explorer | 🏏 Cricket lover",
    followers: 2100,
    following: 600,
    postsCount: 112,
    isVerified: true,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/men/11.jpg",
        caption: "Late night debugging with some ☕ power.",
        likes: 340,
        comments: [
          { user: "sophie_d", text: "Classic dev setup 🔥" },
          { user: "julia.r", text: "Coffee is life 😍" },
        ],
        timestamp: "2h ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/men/12.jpg",
        caption: "Sunday cricket with friends 🏏",
        likes: 520,
        comments: [{ user: "a_mehra", text: "Next time call me too 😎" }],
        timestamp: "1d ago",
      },
    ],
  },
  {
    id: 2,
    name: "Sophie Dubois",
    username: "sophie_d",
    img: "https://randomuser.me/api/portraits/women/24.jpg",
    profession: "Graphic Designer",
    bio: "🎨 Designing stories | 🌸 Aesthetic vibes | ✈️ Exploring creativity everywhere",
    followers: 1340,
    following: 280,
    postsCount: 75,
    isVerified: false,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/women/21.jpg",
        caption: "New poster concept 🌸🎨",
        likes: 410,
        comments: [{ user: "emmawilson", text: "So pretty 😍" }],
        timestamp: "1 day ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/women/22.jpg",
        caption: "My cozy work corner ☕✨",
        likes: 278,
        comments: [{ user: "priya_93", text: "Love the vibes 💡" }],
        timestamp: "4 days ago",
      },
    ],
  },
  {
    id: 3,
    name: "Liam Smith",
    username: "liam_smith",
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    profession: "DevOps Engineer",
    bio: "⚙️ Automating life | ☁️ Cloud native | 🎸 Guitar + Code = Happiness",
    followers: 890,
    following: 455,
    postsCount: 52,
    isVerified: false,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/men/31.jpg",
        caption: "Deployments running smooth ⚡☁️",
        likes: 198,
        comments: [{ user: "chenw", text: "DevOps magic 💪" }],
        timestamp: "3 days ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/men/33.jpg",
        caption: "Weekend jam session 🎸🎶",
        likes: 345,
        comments: [{ user: "amit_s", text: "Bro drop the playlist!" }],
        timestamp: "1 week ago",
      },
    ],
  },
  {
    id: 4,
    name: "Priya Patel",
    username: "priya_93",
    img: "https://randomuser.me/api/portraits/women/45.jpg",
    profession: "UX Designer",
    bio: "✨ Crafting smooth user journeys | 💡 Design thinker | 📷 Aesthetic lover",
    followers: 1765,
    following: 530,
    postsCount: 89,
    isVerified: true,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/women/41.jpg",
        caption: "Wireframes to prototypes 🔥",
        likes: 390,
        comments: [{ user: "julia.r", text: "Super neat flow!" }],
        timestamp: "2 days ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/women/42.jpg",
        caption: "Taking inspiration from nature 🌿",
        likes: 250,
        comments: [{ user: "nina_mu", text: "So refreshing ✨" }],
        timestamp: "6 days ago",
      },
    ],
  },
  {
    id: 5,
    name: "Chen Wei",
    username: "chenw",
    img: "https://randomuser.me/api/portraits/men/59.jpg",
    profession: "Data Scientist",
    bio: "📊 Numbers tell stories | 🤖 AI + ML explorer | 🍜 Food and travel lover",
    followers: 2025,
    following: 720,
    postsCount: 134,
    isVerified: true,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/men/51.jpg",
        caption: "Visualizing datasets 📊",
        likes: 415,
        comments: [{ user: "liam_smith", text: "Clean graphs 🔥" }],
        timestamp: "1 day ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/men/52.jpg",
        caption: "Late-night ramen 🍜",
        likes: 512,
        comments: [{ user: "emmawilson", text: "Food goals 😍" }],
        timestamp: "3 days ago",
      },
    ],
  },
  {
    id: 6,
    name: "Julia Rossi",
    username: "julia.r",
    img: "https://randomuser.me/api/portraits/women/66.jpg",
    profession: "Product Manager",
    bio: "🌍 Traveler | ☕ Coffee lover | Building digital products 🚀",
    followers: 1280,
    following: 340,
    postsCount: 56,
    isVerified: true,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/women/61.jpg",
        caption: "Sunset vibes 🌅✨",
        likes: 245,
        comments: [{ user: "a_mehra", text: "Wow amazing view!" }],
        timestamp: "2 days ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/women/62.jpg",
        caption: "Morning fuel ☕💻",
        likes: 180,
        comments: [{ user: "liam_smith", text: "Best way to start the day!" }],
        timestamp: "5 days ago",
      },
    ],
  },
  {
    id: 7,
    name: "Akash Mehra",
    username: "a_mehra",
    img: "https://randomuser.me/api/portraits/men/76.jpg",
    profession: "Business Analyst",
    bio: "📊 Analyzing trends | 🚀 Growth enthusiast | 🎶 Music keeps me focused",
    followers: 980,
    following: 410,
    postsCount: 43,
    isVerified: false,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/men/71.jpg",
        caption: "Numbers tell the truth 📈",
        likes: 210,
        comments: [{ user: "chenw", text: "That’s insightful 🔍" }],
        timestamp: "3 days ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/men/72.jpg",
        caption: "Beats that keep me focused 🎶",
        likes: 190,
        comments: [{ user: "nina_mu", text: "What’s on the playlist? 👀" }],
        timestamp: "1 week ago",
      },
    ],
  },
  {
    id: 8,
    name: "Emma Wilson",
    username: "emmawilson",
    img: "https://randomuser.me/api/portraits/women/85.jpg",
    profession: "QA Engineer",
    bio: "🛠️ Breaking code to build better software | 📚 Lifelong learner | 🐾 Dog mom",
    followers: 1520,
    following: 389,
    postsCount: 67,
    isVerified: true,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/women/81.jpg",
        caption: "Found it 🐞✔️",
        likes: 275,
        comments: [{ user: "amit_s", text: "QA heroes 🙌" }],
        timestamp: "2 days ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/women/82.jpg",
        caption: "Weekend with my pupper 🐾❤️",
        likes: 420,
        comments: [{ user: "priya_93", text: "Cutest 🥺" }],
        timestamp: "6 days ago",
      },
    ],
  },
  {
    id: 9,
    name: "Carlos Ramirez",
    username: "carlos_rz",
    img: "https://randomuser.me/api/portraits/men/90.jpg",
    profession: "Mobile Developer",
    bio: "📱 Apps for life | ⚡ React Native | 🏖️ Beach + Code weekends",
    followers: 1180,
    following: 370,
    postsCount: 61,
    isVerified: false,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/men/91.jpg",
        caption: "Shipped a new update 🚀📱",
        likes: 300,
        comments: [{ user: "julia.r", text: "Downloading it now!" }],
        timestamp: "3 days ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/men/92.jpg",
        caption: "Work + beach vibes 🏖️",
        likes: 520,
        comments: [{ user: "sophie_d", text: "Dream life 😍" }],
        timestamp: "1 week ago",
      },
    ],
  },
  {
    id: 10,
    name: "Nina Müller",
    username: "nina_mu",
    img: "https://randomuser.me/api/portraits/women/12.jpg",
    profession: "Content Writer",
    bio: "✍️ Words matter | 📚 Storytelling soul | ☕ Coffee & creativity",
    followers: 1420,
    following: 490,
    postsCount: 84,
    isVerified: true,
    requestSent: false,
    isFriend: false,
    posts: [
      {
        id: 1,
        img: "https://randomuser.me/api/portraits/women/13.jpg",
        caption: "Lost in words 📚✍️",
        likes: 340,
        comments: [{ user: "emmawilson", text: "Love your writing style!" }],
        timestamp: "1 day ago",
      },
      {
        id: 2,
        img: "https://randomuser.me/api/portraits/women/14.jpg",
        caption: "Coffee + ideas ☕💡",
        likes: 280,
        comments: [{ user: "amit_s", text: "Classic combo!" }],
        timestamp: "5 days ago",
      },
    ],
  },
];

export default usersJson;
